export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const SET_ACTIVE_LINK = 'SET_ACTIVE_LINK'
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
